version: "3"

networks:
    groceries:

services:
    postgresql:
        image: postgres:12.2
        ports:
            - 5455:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: groceries
        networks:
            - groceries
        volumes:
            - pgdatagroceries:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        ports:
            - 6399:6379
        command: redis-server
        networks:
            - groceries

volumes:
    pgdatagroceries:
