version: "3"

networks:
    lapala:

services:
    postgresql:
        image: postgres:12.2
        ports:
            - 5455:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: lapala
        networks:
            - lapala
        volumes:
            - pgdatalapala:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        ports:
            - 6399:6379
        command: redis-server
        networks:
            - lapala

    pgadmin4:
        image: dpage/pgadmin4
        ports:
            - 3500:80
        environment:
            - "PGADMIN_DEFAULT_EMAIL=root@needone.fr"
            - "PGADMIN_DEFAULT_PASSWORD=root"
        volumes:
            - ./pgadmin/servers.json:/pgadmin4/servers.json
        networks:
            - lapala

volumes:
    pgdatalapala:
